# /my-app/docker-compose.yaml
version: '3'
services:
  web-blue:
    build:
      context: ./blue
    image: my-app:blue
    container_name: web-blue
    ports:
      - "8081:80"
  web-green:
    build:
      context: ./green
    image: my-app:green
    container_name: web-green
    ports:
      - "8082:80"
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"
