version: '3'

services:
  app1:
    image: 'app:v1'
    container_name: app1
    ports:
      - "8001:80"

  app2:
    image: 'app:v1'
    container_name: app2
    ports:
      - "8002:80"

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
