# docker-compose.yaml
version: '3'
services:
  web-blue:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app:blue
    container_name: web-blue
    volumes:
      - ./index_v1.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"
  web-green:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app:green
    container_name: web-green
    volumes:
      - ./index_v2.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"
