version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - blue_app
      - green_app

  blue_app:
    build:
      context: blue
    container_name: blue_app
    ports:
      - "8081:80"

  green_app:
    build:
      context: green
    container_name: green_app
    ports:
      - "8082:80"
